# https://hub.docker.com/_/ubuntu
FROM ubuntu:23.04

MAINTAINER DQNEO

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get -y update \
    && apt install -y tzdata gcc make gdb strace less file xxd bsdmainutils curl \
    && apt-get clean
