# https://hub.docker.com/_/ubuntu
FROM ubuntu:23.04

MAINTAINER DQNEO

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update \
    && apt install -y curl \
    && apt-get clean

RUN curl -L -o go.tar.gz https://go.dev/dl/go1.20.5.linux-amd64.tar.gz \
    && tar xvfz go.tar.gz \
    && rm go.tar.gz \
    && mv go /opt/

RUN echo 'export PATH="/opt/go/bin:$PATH"' >> /etc/bash.bashrc
