FROM dqneo/ubuntu-compiler:latest

RUN curl -L -o go.tar.gz https://go.dev/dl/go1.20.5.linux-amd64.tar.gz \
    && tar xvfz go.tar.gz \
    && rm go.tar.gz \
    && mv go /opt/

RUN echo 'export PATH="/opt/go/bin:$PATH"' >> /etc/bash.bashrc
